config/routes.rb
Pradagency::Application.routes.draw do

  namespace :admin do
    resources :projects do
      member do 
        post "sort"
      end
    end
  end

resources :projects
resources :admin

  root :to => 'admin/projects#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
  has_attached_file :image, 
                    :styles => {:original => "445x440", :small => "98x98"},
                    :url => "/images/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/images/:id/:style_:basename.:extension"
                    
  validates_attachment_size :image, :less_than => 4.megabyte
  validates_attachment_content_type :image, :content_type => /image\/*/
end

app/models/project.rb
class Project < ActiveRecord::Base
    validates_presence_of :client
    validates_presence_of :task
    validates_presence_of :objective
    validates_presence_of :link
    
    has_many :images, :dependent => :destroy,  :order => 'position ASC'
    accepts_nested_attributes_for :images, :allow_destroy => true
    
    has_attached_file :preview, 
                      :styles => { :original => "114x114" },
                      :path  => ":rails_root/public/images/:id/preview/:style_:basename.:extension",
                      :url => "/images/:id/preview/:style_:basename.:extension"
    
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_filter :find_project, :only => [:edit, :update, :destroy, :sort]
  
  def index
    @projects = Project.all(:order => "created_at ASC")
  end

  def new
    @project = Project.new
    @project.images.build
    @image_counter = 0
  end

  def create
    @project = Project.new(params[:project])
    if @project.save 
      redirect_to admin_projects_path, :notice => "Проект успешно добавлен" 
    else 
      render :action => "new"
    end
  end

  def edit
    @image_counter = @project.images.size
    @images = @project.images.order('images.position ASC')
  end

  def update
    if @project.update_attributes(params[:project])
      if params[:delete_ids] != nil
        delete_ids = params[:delete_ids]
        delete_ids.each do |del|
          image = @project.images.find_by_id(del)
          image.destroy
        end
      end
     redirect_to admin_projects_path, :notice => "Проект успешно отредактирован"
    else
     render :action => "edit"
    end
  end

  def destroy
    if @project.delete
      notice = "Проект успешно удален"
    else
      notice = "С удалением что-то не так"
    end
    redirect_to admin_projects_path, :notice => notice
  end

  def sort
    @images = @project.images.all
    @images.each do |image|

      image.update_attribute(:position, params['image'].index(image.id.to_s) + 1)
  end

  render :nothing => true
  end
  
  private
  
  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
    @project = Project.find(params[:id])
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<%= link_to "Projects", admin_projects_path %>

app/views/admin/projects/_form.html.erb
<% if @project.errors.any? %>
 <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<p>
	<%= f.label :client %>
	<%= f.text_field :client %>
</p>
<br>
<p>
	<%= f.label :task %>
	<%= f.text_field :task %>
</p>
<br>
<p>
	<%= f.label :objective %><br>
	<%= f.text_area :objective %>
</p>
<br>
<p>
	<%= f.label :link %>
	<%= f.text_field :link %>
</p>
<p>
	<%= f.label :preview %>
	<%= f.file_field :preview %>
</p>

<p>png/jpg/gif не более 4 Мб:<br>
Можно выбрать несколько сразу</p>
Images&nbsp;
<%= file_field_tag 'project[images_attributes][][image]', :multiple => true %>
<% if controller.action_name =~ /update|edit/ %>

<ul id="images">
		<% @project.images.each do |image_delete| %>
		 	<% if image_delete.id != nil %>
				<br><li id="image_<%= image_delete.id %>"><span class="handle">[drag]</span>
				<%= image_tag image_delete.image.url(:small, false) %>
		        <br>Удалить изображение <input name="delete_ids[]" type="checkbox" value="<%= image_delete.id %>" /><br><br>
		 <% end %>
		<% end %>
</ul>



<% end %>
<p>
	<%= f.submit "Сохранить" %>
</p>

app/views/admin/projects/edit.html.erb
<h1>Редактирование проекта</h1>
<% content_for :javascript do %>
	<%= javascript_tag do %>
	// Sorting the list

	$(document).ready(function(){
		$('#images').sortable({
			axis: 'y',
			dropOnEmpty: false,
			handle: '.handle',
			cursor: 'crosshair',
			items: 'li',
			opacity: 0.4,
			scroll: true,
			update: function(){
				$.ajax({
					type: 'post',
					data: $('#images').sortable('serialize'),
					dataType: 'script',
					complete: function(request){
						$('#images').effect('highlight');
					},
					url: 'sort'})
				}
			});
		});
		<% end %>
<% end %>

<%= form_for(@project, :url => admin_project_path(@project)) do |f| %>
 <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/admin/projects/index.html.erb
<h1>Проекты</h1>
<%= notice %><br><br>
<%= link_to "Создать новый проект", new_admin_project_path %>
<% @projects.each do |project| %>
<table border="0" cellspacing="2" cellpadding="2">
	<tr>
		<td>Project&nbsp;&nbsp;<%= link_to project.task, project_path(project) %></td>
		<td>|&nbsp;<%= link_to "edit", edit_admin_project_path(project)%></td>
		<td>|&nbsp;<%= link_to "delete", admin_project_path(project), :confirm => 'Вы действительно хотите удалить проект?', :method => :delete %></td>
	</tr>
	<tr>
		<td>for&nbsp;<i><%= project.client %></i></td>
	<tr>
</table>
<% end %>

app/views/admin/projects/new.html.erb
<h1>Новый проект</h1>

<%= form_for(@project, :url => admin_projects_path) do |f| %>
 <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pradagency</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js", "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield :javascript %>
<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/show.html.erb
<table border="0" cellspacing="2" cellpadding="2">
	<tr>
		<td>Клиент:&nbsp;<%= @project.client %></td>
	<tr>
	<tr>
		<td>Проект:&nbsp;&nbsp;<%= @project.task %></td>
	</tr>
	<tr>
		<td>Задача:&nbsp;&nbsp;<%= @project.objective %></td>
	</tr>
	<tr>
		<td><%= link_to @project.link, @project.link %></td>
	</tr>
	
</table>
<%= image_tag @project.preview.url %>